### ISSUE TITLE
test t7

### ISSUE THREAD

**Issue by mortentysse** [denoptim-project/DENOPTIM#2]
Running t7 on MacOS Darwin.

dg_96 is the following:
96 1_1_0_-1,2_4_1_0,8_4_1_0,3_3_1_0,7_1_2_0,17_1_2_1,14_2_1_1,18_1_2_1,10_1_2_1,11_3_1_1,151_1_2_2,152_1_2_2,153_1_2_2, 1_0_2_0_1_co:0_coa:1,1_3_8_0_1_co:0_coa:1,1_1_3_0_1_ccb:0_cca:0,1_2_7_0_1_ch:0_hyd:1,3_2_17_0_1_ch:0_hyd:1,3_1_14_0_1_ccb:0_ATminus:0,3_3_18_0_1_ch:0_hyd:1,2_1_10_0_1_cob:1_hyd:1,8_1_11_0_1_cob:1_cca:0,11_1_151_0_1_ccb:0_hyd:1,11_2_152_0_1_ch:0_hyd:1,11_3_153_0_1_ch:0_hyd:1,  => 96 16 [3, 0, 1]

which is properly converted to SDF file:

  CDK     0625191250

 13 12  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0001    0.0001    0.0001 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0001    0.0001    0.0001 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0001    0.0001    0.0001 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1930   -2.4982    1.1563 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.1930   -2.4982    1.1563 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0001    0.0001    0.0001 ATM 0  0  0  0  0  0  0  0  0  0  0  0
    0.1930   -2.4982    1.1563 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.1930   -2.4982    1.1563 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0001    0.0001    0.0001 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1930   -2.4982    1.1563 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.1930   -2.4982    1.1563 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.1930   -2.4982    1.1563 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  1  4  1  0  0  0  0
  1  5  1  0  0  0  0
  4  6  1  0  0  0  0
  4  7  1  0  0  0  0
  4  8  1  0  0  0  0
  2  9  1  0  0  0  0
  3 10  1  0  0  0  0
 10 11  1  0  0  0  0
 10 12  1  0  0  0  0
 10 13  1  0  0  0  0
M  END
> <GCODE>
96

> <GraphENC>
96 1_1_0_-1,2_4_1_0,8_4_1_0,3_3_1_0,7_1_2_0,17_1_2_1,14_2_1_1,18_1_2_1,10_1_2_1,11_3_1_1,151_1_2_2,152_1_2_2,153_1_2_2, 1_0_2_0_1_co:0_coa:1,1_3_8_0_1_co:0_coa:1,1_1_3_0_1_ccb:0_cca:0,1_2_7_0_1_ch:0_hyd:1,3_2_17_0_1_ch:0_hyd:1,3_1_14_0_1_ccb:0_ATminus:0,3_3_18_0_1_ch:0_hyd:1,2_1_10_0_1_cob:1_hyd:1,8_1_11_0_1_cob:1_cca:0,11_1_151_0_1_ccb:0_hyd:1,11_2_152_0_1_ch:0_hyd:1,11_3_153_0_1_ch:0_hyd:1,

> <GraphMsg>
NEW

$$$$

but runt7.sh  expects SDF file with ' 16 15  0  0  .  0  0  0  0 '

**Comment by mortentysse** [comment]
java version "12.0.1" 2019-04-16

**Comment by marco-foscato** [comment]
I've change the overall strategy for t7 (commit 4698fb930ca033bf716e461499de2694dcbad53c ). The input, which is a serialized graph, is now created on the fly from a simple FSE run that was added to the test folder as p7. The serialized graph that is used as the input for t7 is the only one of its level that converts in to a molecule, thus removing any source of ambiguity.
