### ISSUE TITLE
Different addAP(…) methods

### ISSUE THREAD

**Issue by einarkjellback** [denoptim-project/DENOPTIM#48]
Fragment has an addAP(…)-method with a different signature then the addAP(…)-method it inherits from Vertex. These methods also have different behaviors related to issue #49. We should definitely unify both the syntax and behavior of these methods.

I suggest we keep the signature from Vertex except for substituting the type of the direction vector parameter from []double to Point3d as Fragment's signature uses. Point3d better conveys that the direction vector is a 3-dimensional vector than []double, both in name and implementation.

**Comment by marco-foscato** [comment]
Refactoring all addAP methods in ed22449d174f0dd0b5e1a20c998cee275970bb44, still not ideal, but better that before.
Also introducing use of Point3d in 4c01445
