### ISSUE TITLE
Inconsistent order of list of attachment points

### ISSUE THREAD

**Issue by einarkjellback** [denoptim-project/DENOPTIM#50]
While working on a method I had to sort the list of attachment points belonging to the Fragments that constitute the inner graph of a Template, the code broke in several places (reported by @marco-foscato). @marco-foscato suggested that there are several places where it is assumed that the list of APs is in order of the AP ID, i.e. in the order of AP creation.

We should find a solution that prevents programmers from inadvertently changing the order of the APs.

One solution is to change the type of the data structure that stores the APs to one that enforces a particular ordering. An example of such a data structure can be a heap.

Another work-around is to let .getAttachmentPoints() return a copy of the AP list. This will incur a small performance loss, but will solve the problem. It is also generally considered good practice to return copies instead of references of objects' fields from getters.

The last possibility is to get rid of the assumption altogether and change the code where the assumption is made.

**Comment by marco-foscato** [comment]
The fixed order of the attachment point is a well-rooted convention in DENOPTIM. This convention will not change.
