### ISSUE TITLE
Running tests on W10

### ISSUE THREAD

**Issue by agiani99** [denoptim-project/DENOPTIM#89]
HI everyone
running suggested runAllTests.sh from git Bash shell does not complete. Can you test it?
Is it something that has to do with specific bash requirements or runAllTests.sh has been created only for Mac/Linux?
Best
andrea

**Comment by marco-foscato** [comment]
Hi Andrea, 
yes, the script was born on Unix systems and several tests can be run only on Mac/Linux computers. This is due entirely to the fact that the checks performed on the results of denoptim's calculations are done using Bash functionality that is not available on GitBash.
Moreover, it is meant to test a local built of denoptim, not the installation obtained from conda. 
So, after building denoptim with maven on GitBash, the runAllTests.sh script should run only those tests that can be run there (namely: t2b, t2c, t12a, t12c, t14-t26, t28, t29). 
I just tried, and it took around 4 min to complete. Still, it is entirely possible that there is some GitBash tweak going wrong on your system. Could you be more specific as to where and how it fails to complete?

Best regards,
Marco

**Comment by marco-foscato** [comment]
closing the issue according to email from Andrea.
